### PR TITLE
Add anchors to headings

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done

- Add anchors to headings
- Changed copyright date in the footer to 2019

## QA

- Pull branch
- Run `./run serve`
- View http://0.0.0.0:8033/installing
- Verify that headers are clickable and the anchors works

Fixes https://github.com/canonical-web-and-design/juju-squad/issues/704

### CODE REVIEW

**Review by hatched — APPROVED** [review]

**Comment by nottrobin** [comment]
Thanks @barrymcgee for the suggestion. There's a fair bit of history and context here (as I've previous discussed with @hatched).

The fundamental problem with this approach is that all the documentation content comes from [the "docs" category in Discourse](https://discourse.jujucharms.com/c/docs). The version of documentation that lives in Discourse is no less a true representation of the documentation, and the community are absolutely just as welcome to browse and read it there as they are to read it on docs.jujucharms.com (or jaas.ai/docs, as it will be before the end of the week).

For this reason, we do very little transformation to the content we pull in from Discourse, so that both places continue to work sensibly.

The trouble with any solution to adding heading link IDs that only applies to docs.jujucharms.com/jaas.ai.docs and not Discourse is that it will inevitably lead to people making use of those IDs in internal links in the documentation content. These links will then work only in the site, and not work within Discourse. In some cases this could be very confusing.

Therefore, the only solution to adding heading IDs we have for now is to follow [the Discourse official recommendation](https://meta.discourse.org/t/deep-linking-to-headings-anchors/47552), which is to manually use the following markup inside the documentation topic content:

``` html
<h3 id='heading--link-to-me'>Link to me</h3>
```

I am aware this is less than ideal. But the ideal fix is for Discourse to add the function to automatically generate IDs for headings, so that when we pull the HTML from Discourse it comes pre-cooked with these IDs.

Unfortunately, it looks like this change needs to be made in CommonMark before it can be in Discourse - but @coding-horror [appears to support the idea](https://talk.commonmark.org/t/feature-request-automatically-generated-ids-for-headers/115/8), so it might happen someday.

I'll close this for now, but we can continue discussion if you like.

**Comment by nottrobin** [comment]
I misunderstood this PR, and have deleted my previous comment. This work looks great, thanks.

Personally, my preferred design (and I think @anthonydillon's too) would be to leave the headings as black, not make them links themselves, but instead have the anchor icon appear when you hover over the row, and then the anchor icon becomes the link. I think this is the more common pattern - e.g. how GitHub do it on READMEs e.g. [the maas.io readme](https://github.com/canonical-web-and-design/maas.io/):

local-development

But we can see what a designer thinks.

**Comment by anthonydillon** [comment]
Yes I feel having the entire title a link is intrusive and the link should just be on the icon.

**Comment by spencerbygraves** [comment]
@barrymcgee I agree with @nottrobin and @anthonydillon, the idea was for it to work like Github. Thanks.

**Comment by barrymcgee** [comment]
Okey-doke - refactored and pushed, please re-review.

**Review by spencerbygraves — APPROVED** [review]

**Comment by nottrobin** [comment]
@barrymcgee I have some good news and some bad news.

The good news is that this PR looks great. The bad is that docs.jujucharms.com has moved to jaas.ai/docs - https://github.com/canonical-web-and-design/jaas.ai/blob/master/templates/docs/document.html.

I leave it up to you and @tbille to coordinate how we move this work over to jaas.ai =)

**Comment by barrymcgee** [comment]
@tbille Ant mentioned in our stand-up that you intend to shift this work across to the new repo - is that right?

**Comment by nottrobin** [comment]
I believe this work has moved here: https://github.com/canonical-web-and-design/jaas.ai/pull/395

Closing for now. Reopen if you disagree.

**Pull request closed without merging**
