### PR TITLE
Edit doc content links

### PR DESCRIPTION
**Pull request by pmatulis**
I merged two sections of links. I have no way of building the site to see if everything lines up correctly.

### CODE REVIEW

**Comment by pmatulis** [comment]
The demo shows a lot of whitespace on the right. I think it would be best to make two columns again (5 and 4 rows each) but keep to just one heading ("Doc updates").

**Comment by pmatulis** [comment]
[Update links on Docs home page](https://trello.com/c/RAvHOVX5/1349-update-links-on-docs-home-page)

**Comment by nottrobin** [comment]
@pmatulis like this? https://docs-jujucharms-com-canonical-web-and-design-pr-16.run.demo.haus/ - https://github.com/canonical-web-and-design/docs.jujucharms.com/pull/16

**Comment by pmatulis** [comment]
@nottrobin :+1: I'll take note of the HTML required to do that...

Btw, I noticed that the special construction emoji [shows up](https://docs-jujucharms-com-canonical-web-and-design-pr-16.run.demo.haus/clouds). My understanding was that it hides the note.

**Comment by nottrobin** [comment]
@pmatulis If you want that content *displayed in the forum* but *stripped from the documentation site*, then the format is, specifically:

``` html
<blockquote>
  <p>
    <img title=":construction:" class="emoji" ...>
    <strong>NOTE TO EDITORS</strong>
    <img title=":construction:" class="emoji" ...>
  </p>
  <p>{content}</p>
</blockquote>
```

Or, in Markdown:

``` markdown
> :construction: **NOTE TO EDITORS** :construction:
>
> {content}
```

Or:

``` markdown
[quote]
:construction: **NOTE TO EDITORS** :construction:

{content}
[/quote]
```

(Source code here: https://github.com/canonical-web-and-design/canonicalwebteam.discourse-docs/blob/master/canonicalwebteam/discourse_docs/parsers.py#L219)

I wasn't super keen to add this format in the first place, I much prefer the pattern of using an HTML comment in the source, e.g.:

``` html
<--
TODO

- Bug tracking: https://bugs.launchpad.net/juju/+bug/1749302
...
-->
```

So that it only shows up to people actually editing the page and the forum wiki topics themselves remain clean and as similar to the resulting documentation page as possible - I think this is actually a nicer experience for *readers* of the forum.

But Gustavo felt strongly that he wanted "NOTE TO EDITORS" sections displayed in certain cases.

For the time being I'd rather not make this parser any more greedy and keep that pattern specific to "NOTE TO EDITORS" sections - to keep internal notes from polluting the forum topic, and keep the number of differences between how a post renders in the format and how it renders on the site as small as possible.

I'd suggest that in this case, for "TODO" lists, an HTML comment is the way to go, because it really is only relevant to people actually working on the topic, not people reading it. Would you be happy to change change it to an HTML comment?

**Pull request closed without merging**
